### PR TITLE
New Function "alarm"

### PR DESCRIPTION
**Pull request by DiceBotReporter**
Allows Users to play alarm from Lua Script.

alarm("alarm.mp3")

### CODE REVIEW

**Comment by Seuntjie900** [comment]
There's no error handling of any kind. Which means the bot is going to crash if the file doesn't exist (actually crash, not just give a LUA error) or the file is in the incorrect format, like a WAV. There's an existing playalarm function that pulls from the file you can choose in the settings window with proper error handling. Why not link the new lua function to the playalarm method that already exists?

While your at it, why not add a function to play the ching sound file that is currently located in the Withdraw function. My suggestion would be to create a PlayChing method in cDiceBot.cs that does handles playing the sound (with error handling) then call that method from Withdraw instead of duplicating the code, as well as from the LUA function for the ching sound.

That also allows you to remove the parameter for the function call (so just alarm() or ching()) as well as create a new method (playsound('filename') that allows the user to specify a sound file to play should it be required. With error handling of course.

**Comment by Seuntjie900** [comment]
Have you made any progress on this? I plan on releasing a new update this weekend, if you can get it finished by then it would be great.

**Comment by DiceBotReporter** [comment]
I Was on holiday came back today i will try to make it before Saturday.

**Comment by DiceBotReporter** [comment]
What im thinking is that the custom play alarm function is not required only ching() and alarm() should be enough because if we do customplay function it will be hard for users to use.

**Comment by Seuntjie900** [comment]
Still no error handling which is going to cause the bot to crash. The filebrowserdialog will also cause the bot to stop/delay betting until the user selects a file. This is going to cause trouble with auto retrying bets and things

**Comment by Seuntjie900** [comment]
see 603fac72ac6c4c23a7ce666db18ada5071aa9dde

**Comment by Seuntjie900** [comment]
I liked the idea about the single use file browser dialog, I just think it's going to cause too many problems

**Comment by DiceBotReporter** [comment]
You are right but this is what i can do at the moment also im not skilled like you in C#

**Comment by Seuntjie900** [comment]
Meant to link to this commit: https://github.com/Seuntjie900/DiceBot/commit/57ab57ce50fd7dbb7e6e0eaf1cf20bc232c472ba

**Comment by DiceBotReporter** [comment]
Yep i saw it now its good and i tried it works :)

**Pull request closed without merging**
