### PR TITLE
Customizable UserInput GUI

### PR DESCRIPTION
**Pull request by DiceBotReporter**
Old Use of "read" and new Command "advread" are working.
Overloaded the ShowDialog and synced with latest commits.

### CODE REVIEW

**Comment by Seuntjie900** [comment]
Made a few small changes to this on the master branch

**Comment by DiceBotReporter** [comment]
I Can't see the changes you made on Commits page forgive me.

**Comment by Seuntjie900** [comment]
Forgot to push, sorry. https://github.com/Seuntjie900/DiceBot/commit/1d4d9ab12ca92676678a0476383c7841219fae00

**Comment by DiceBotReporter** [comment]
O yeah i see now.
Yes it looks more clear.Thanks for upgrade :)

I Will try to work on multi lang support tomorrow.

**Pull request merged**
