### PR TITLE
Customizable UserInput

### PR DESCRIPTION
**Pull request by DiceBotReporter**
With This Update You can almost change everything in the User Input GUI.

Use of code.
`read("prompt","userinputext","btncanceltext","btnoktext",1)`
Example:
```
nextbet=0.00000001
function dobet()
read("prompt","userinputext","btncanceltext","btnoktext",1)
stop()
end
```

### CODE REVIEW

**Comment by Seuntjie900** [comment]
This is a cool idea but writing the options to a text file is slow and unnecessary. How about making an overloaded version of the ShowDialog function with the extra parameters. As well as making this call an overloaded call in LUA so that the user can use the default options without setting them if he/she doesn't want to change the text.

**Comment by DiceBotReporter** [comment]
Couldn't find way to do it in UserInput.Designer.cs if you can please do it :)

**Comment by Seuntjie900** [comment]
Well try it in UserInput.cs then

**Comment by DiceBotReporter** [comment]
I Tried it before too but there is one problem you cant set UserInput Form Text anywhere else from UserInput.Designer.cs

**Comment by DiceBotReporter** [comment]
Okay i found a way thanks :) 

Will do new pull request when i complete it

**Pull request closed without merging**
