### PR TITLE
Customizable UserInput [Updates]

### PR DESCRIPTION
**Pull request by DiceBotReporter**
I Tried to make it the way, you want me to :)

New use:
`advread("prompt",type,"userinputext","btncanceltext","btnoktext")`

Or if you want without this settings
`read("prompt",type)`

Couldn't test it because of new issue.  [İssue](https://github.com/Seuntjie900/DiceBot/issues/24)

### CODE REVIEW

**Comment by Seuntjie900** [comment]
Please sync with my latest commit and test both the advanced and normal read functions

**Comment by DiceBotReporter** [comment]
Okay testing now
And I will try overload method also

**Comment by Seuntjie900** [comment]
You can also call the new overloaded method, set the button texts and then call the original showdialog function. There's no need to duplicate the code. It makes it harder to maintain in the future

**Comment by DiceBotReporter** [comment]
I Got my brain burned but no luck for me

It give this error when i try to overload it 

"No overload for method 'ShowDialog' takes 5 arguments"

**Comment by DiceBotReporter** [comment]
I Did Everything Updated my Pull Request Both of them are works.
@Seuntjie900

**Comment by Seuntjie900** [comment]
Please sync this branch with master and do the pull request again

**Pull request closed without merging**
